/* eslint-disable @typescript-eslint/no-explicit-any */
import { createContext } from "preact";

interface IContext {
  currentDocument: string;
  currentPage: string;
  currentUser: any;
  documentationData: any;
  documentationId: string;
  documentationTitle: string;
  isBuilding: boolean;
  isContenFromServerOpen: boolean;
  isCurrentNameValid: boolean;
  isDraft: boolean;
  isFromSavedData: boolean;
  isIndexOpen: boolean;
  isLoading: boolean;
  isLoginPageOpen: boolean;
  isMainContentOpen: boolean;
  isPdSectionOpen: boolean;
  isPreviewing: boolean;
  isReset: boolean;
  isScroll: boolean;
  isSettingsPageOpen: boolean;
  isWip: boolean;
  loggedInUser: string;
  previewData: any;
  selectedCard: string;
  selectedElement: any;
  selectedElementName: string;
  selectedMasterId: string;
  selectedSections: any[];
  setCurrentDocument: any;
  setCurrentPage: any;
  setCurrentUser: any;
  setDataForUpdate: any;
  setDocumentationData: any;
  setDocumentationId: any;
  setDocumentationTitle: any;
  setIsBuilding: any;
  setIsContenFromServerOpen: any;
  setIsCurrentNameValid: any;
  setIsDraft: any;
  setIsFromSavedData: any;
  setIsIndexOpen: any;
  setIsLoading: any;
  setIsMainContentOpen: any;
  setIsPdSectionOpen: any;
  setIsPreviewing: any;
  setIsReset: any;
  setIsSettingsPageOpen: any;
  setIsWip: any;
  setLoggedInUser: any;
  setPreviewData: any;
  setSelectedCard: any;
  setSelectedElement: any;
  setSelectedElementName: any;
  setSelectedMasterId: any;
  setSelectedSections: any;
  setShowCancelPopup: any;
  setShowDeleteAccountPopup: any;
  setShowPreviewPopup: any;
  setShowResetPopup: any;
  setToken: any;
  showCancelPopup: boolean;
  showDeleteAccountPopup: boolean;
  showPreviewPopup: boolean;
  showResetPopup: boolean;
  token: string;
  dataForUpdate: any;
}

const BuilderContext = createContext<IContext | null>(null);

export default BuilderContext;
